# 노드 스펙: 16vCore 64GB
# 노드 5개 기준 설정
resources:
  requests:
    cpu: "550m"
    memory: "1536Mi" #1.5G
  limits:
    memory: "2304Mi" #2.25G
hpa:
  enabled: true
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 75