apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc-test
  namespace: sonarqube
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ktc-nfs-client