USER-SUPPLIED VALUES:
compactor:
  enabled: true
  extraArgs:
  - -config.expand-env=true
  extraEnv:
  - name: MY_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  replicas: 1   # 개수가 늘어날 수록 S3로 호출하는 양이 많아짐. 모니터링 후 늘리는 것을 추천
  # 보관주기
  config:
    compaction:
      block_retention: 168h # 원하는 기간 설정 (예: 168h = 7일, 720h = 30일) / trace는 로그보다 쌓이는 데이터 양이 매우 많으므로 1주일 이상은 추천하지 않음
distributor:
  config:
    log_received_spans:
      enabled: true   # 모든 spans를 tempo-distributor에 로그로 남기므로 개발환경에서 모니터링할때만 사용, 운영 시에는 loki 로그 양이 너무 많아질 수 있음
  extraArgs:
  - -config.expand-env=true
  extraEnv:
  - name: MY_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  # 서비스에 kong 주석 추가
  # grpc는 HTTP/2 사용하여 kong이 HTTP/1.1이 아닌 HTTP/2로 받을 수 있어야함
  service:
    annotations:
      konghq.com/protocol: "grpc"
  replicas: 3
  strategy: # 새 파드 추가 시 pending현상을 막기 위해 아래 설정 추가(distributor는 동일 노드에 파드를 중복해서 띄우지 않음)
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0          # 업데이트 중 추가 파드 생성 허용 수: 0
      maxUnavailable: 1    # 업데이트 중 일시 정지 허용 파드 수: 1
gateway:
  enabled: true
  replicas: 3
  strategy: # 새 파드 추가 시 pending현상을 막기 위해 아래 설정 추가(동일 노드에 파드를 중복해서 띄우지 않음)
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0          # 업데이트 중 추가 파드 생성 허용 수: 0
      maxUnavailable: 1    # 업데이트 중 일시 정지 허용 파드 수: 1
global:
  clusterDomain: cluster.local
  image:
    pullSecrets:
    - harbor-secret
    registry: <harbor repository_url>/helm-images
  storageClass: ktc-nfs-client
ingester:
  extraArgs:
  - -config.expand-env=true
  extraEnv:
  - name: MY_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  replicas: 3
  strategy: # 새 파드 추가 시 pending현상을 막기 위해 아래 설정 추가(동일 노드에 파드를 중복해서 띄우지 않음)
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0          # 업데이트 중 추가 파드 생성 허용 수: 0
      maxUnavailable: 1    # 업데이트 중 일시 정지 허용 파드 수: 1
  # 기본값은 보통 10s~15s 내외입
  # 프론트엔드와 백엔드 데이터가 도착하는 시차가 있더라도, 템포가 하나의 트레이스로 묶어주기 위해 기다리는 시간
  trace_idle_period: 30s
  # 전체 데이터 저장용 5분단위로 끊어서 s3에 저장
  max_block_duration: 5m
memcached:
  replicas: 3
minio:
  enabled: false
querier:
  extraArgs:
  - -config.expand-env=true
  extraEnv:
  - name: MY_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  frontend:
    enabled: true
    replicas: 3
  replicas: 3
  strategy: # 새 파드 추가 시 pending현상을 막기 위해 아래 설정 추가(동일 노드에 파드를 중복해서 띄우지 않음)
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0          # 업데이트 중 추가 파드 생성 허용 수: 0
      maxUnavailable: 1    # 업데이트 중 일시 정지 허용 파드 수: 1
storage:
  trace:
    backend: s3
    s3:   # kt 오브젝트 스토리지
      access_key: <s3_access_key>
      bucket: dev-tempo-trace
      endpoint: obj-g-1.ktcloud.com   # http or https 작성하지 않고, 아래 insecure 옵션으로 대신함
      insecure: false     # http면 true, https면 false로 설정
      secret_key: <s3_secret_key>
      tls_insecure_skip_verify: true
traces:
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  zipkin:
    enabled: false    # spring sleuth 사용 시 true

# 헬름 차트에 없는 커스텀 K8s 오브젝트를 강제로 끼워 넣는 옵션
# 업무클러스터에서 관리클러스터의 distributor로 통신할 수 있도록 설정
extraObjects:
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: tempo-grpc-ingress
      annotations:
        konghq.com/protocols: "grpc"
    spec:
      ingressClassName: "default"
      rules:
      - host: tempo.dev.re.kr
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                # 실제 생성된 distributor 서비스 이름
                name: tempo-distributor
                port:
                  number: 4317