apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: remove-sensitive-headers-mgmt
  namespace: Namespace_B
  annotations:
    kubernetes.io/ingress.class: mgmt
    konghq.com/tags: ''  
  labels:
    global: "true"
plugin: response-transformer
config:
  remove:
    headers:
      - x-powered-by
      - x-envoy-upstream-service-time
      - server
      - x-nextjs-cache
      - x-nextjs-prerender
      - x-nextjs-stale-time
      - vary