apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-basic-ba-nb
  namespace: argocd
spec:
  ignoreDifferences:
  - group: argoproj.io
    kind: Rollout
    jsonPointers:
    - /spec/replicas
  project: default
  sources:
    - repoURL: http://<DR Git Reository URL>/infra/adnp-charts.git
      targetRevision: HEAD
      path: frontend
      helm:
        valueFiles:
          - '$values/helm/values.yaml'
          - '$values/helm/values-dr.yaml'
    - repoURL: http://<DR Git Reository URL>/frontend/basics-ba-nb.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://<destination server ip>:6443
    namespace: Namespace_A
  syncPolicy:
    automated:
      prune: true
      selfHeal: true