apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-runner-config
  namespace: gitlab-runner
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ktc-nfs-client