apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inaea-backend-proxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://<Git Repository URL>/frontend/inaea-backend-proxy.git
    targetRevision: HEAD
    path: helm
  destination:
    server: https://<destination server ip>:6443
    namespace: Namespace_B
  syncPolicy:
    automated:
      prune: true
      selfHeal: true