apiVersion: v1
kind: Service
metadata:
  name: docker-svc
  namespace: gitlab-runner
spec:
  ports:
  - name: docker-daemon
    nodePort: 30333
    port: 2375
    protocol: TCP
    targetPort: 2375
  selector:
    app: docker
  type: NodePort