apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-runner-nfs-pvc
  namespace: gitlab-runner
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ktc-nfs-client