apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-runner-dev-eform-pvc
  namespace: gitlab-runner
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-runner-stg-eform-pvc
  namespace: gitlab-runner
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""