prometheus:
  url: http://prometheus-server.prometheus.svc.cluster.local
  port: 80
  path: /prometheus
rules:
  custom:
    - seriesQuery: 'kong_http_requests_total{pod!="",namespace!=""}'
      resources:
        overrides:
          namespace:
            resource: {resource: "namespace"}
          pod:
            resource: {resource: "pod"}
      name:
        matches: "^(.*)_total"
        as: "${1}_per_second"
      metricsQuery: 'sum(rate(<<.Series>>{<<.LabelMatchers>>}[2m])) by (<<.GroupBy>>)'
image:
  repository: <harbor-registry>/helm-images/prometheus-adapter
  tag: v0.12.0