---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: Namespace_B
spec:
  encryptedData:
    db-password: AgA3...<ENCRYPTED_DATA_PLACEHOLDER>...==
  template:
    metadata:
      name: db-secret
      namespace: Namespace_B
