applicationName: a-spring
replicaCount: 3
image:
  repository: <Registry URL>/administrator/a-spring
  tag: prd-20260409_191157
  pullPolicy: IfNotPresent
service:
  port: 8919
ingress:
  enabled: true
  hosts:
    - host: "a-spring.backend"
      paths:
        - path: "/"
          pathType: Prefix
    - host: "a-spring.api.com # PKI통신용
      paths:
        - path: "/"
          pathType: Prefix
    - host: "a-spring.Namespace_A.svc"
      paths:
        - path: "/"
          pathType: Prefix
extraIngress:
  - name: "upload"
    hosts:
      - host: "a-spring.backend"
        paths:
          - path: "/api/v1/cm/attach/fileHandler"
            pathType: Prefix
      - host: "a-spring.api.com"
        paths:
          - path: "/api/v1/cm/attach/fileHandler"
            pathType: Prefix
      - host: "a-spring.Namespace_A.svc"
        paths:
          - path: "/api/v1/cm/attach/fileHandler"
            pathType: Prefix
resources:
  requests:
    cpu: "1000m"
    memory: "3072Mi" #3G
  limits:
    memory: "5120Mi" #5G
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 65
wasTrace:
  traceId: "a-spring
  site: "a"
  mountPath: "/app/wt/config/a/settings.ini"
secretEnvs:
	- envName: "SPRING_RO_DATASOURCE_PASSWORD"
		name: "db-secret"
		key: "db-password"
	- envName: "SPRING_RW_DATASOURCE_PASSWORD"
		name: "db-secret"
		key: "db-password"
env:
  - name: SPRING_RO_DATASOURCE_URL
    value: "jdbc:postgresql://<slave ip>:<db port>,<master ip>:<db port>/dadnp?targetServerType=preferSecondary&tcpKeepAlive=true&connectTimeout=5&socketTimeout=30&ApplicationName=backend-basic-cm-sy"
  - name: SPRING_RO_DATASOURCE_USERNAME
    value: "<db user>"
  - name: SPRING_RW_DATASOURCE_URL
    value: "jdbc:postgresql://<master ip>:<db port>,<slave ip>:<db port>/dadnp?targetServerType=primary&tcpKeepAlive=true&connectTimeout=5&socketTimeout=30&ApplicationName=backend-basic-cm-sy"
  - name: SPRING_RW_DATASOURCE_USERNAME
    value: "<db user>"
  - name: SPRING_RW_DATASOURCE_PASSWORD
    value: "<db password>"
  - name: JAVA_TOOL_OPTIONS
    value: "-XX:InitialRAMPercentage=50.0 -XX:MaxRAMPercentage=60.0"
  - name: SPRING_RO_DATASOURCE_MAXIMUMPOOLSIZE
    value: "5"
  - name: SPRING_RO_DATASOURCE_MINIMUMIDLE
    value: "3"
  - name: SPRING_RW_DATASOURCE_MAXIMUMPOOLSIZE
    value: "5"
  - name: SPRING_RW_DATASOURCE_MINIMUMIDLE
    value: "3"