{{- range .Values.services }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: default
    konghq.com/strip-path: "{{ .stripPath }}"
    konghq.com/preserve-host: "true"
    konghq.com/plugins: "{{ .name }}-transformer"
  name: {{ .name }}-proxy
  namespace: {{ .namespace }}
spec:
  rules:
  - host: "{{ .host }}"
    http:
      paths:
      - path: "{{ .path }}"
        pathType: Prefix
        backend:
          service:
            name: {{ .name }}-backend
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: mgmt
    konghq.com/strip-path: "{{ .stripPath }}"
    konghq.com/preserve-host: "true"
    konghq.com/plugins: "{{ .name }}-transformer"
  name: {{ .name }}-proxy-mgmt
  namespace: {{ .namespace }}
spec:
  rules:
  - host: "{{ .host }}"
    http:
      paths:
      - path: "{{ .path }}"
        pathType: Prefix
        backend:
          service:
            name: {{ .name }}-backend
            port:
              number: 80
{{- end }}
