{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.applicationName }}-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.applicationName }}
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ .Values.applicationName }}
  
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}
  
  # {{- if .Values.hpa.targetMemoryUtilizationPercentage }}
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: Utilization
  #       averageUtilization: {{ .Values.hpa.targetMemoryUtilizationPercentage }}
  # {{- end }}
  
  {{- if .Values.hpa.behavior }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.hpa.behavior.scaleUp.stabilizationWindowSeconds }}     
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.behavior.scaleDown.stabilizationWindowSeconds }}
      selectPolicy: Max
      policies:
        - periodSeconds: 60           # 1분마다 검사
          type: Percent
          value: 25                   # 현재 파드 수의 25%까지만 한 번에 삭제
  {{- end }}

{{- end }}